data:
  train_size: 800
  val_size: 200
  # path: "/home/yixuan.sun/projects/neuralPrecond/Dirac/"
  path: "/Users/yixuan.sun/Documents/projects/Preconditioners/datasets/Dirac/"

model:
  hidden_layers: [128, 128, 128, 128] 
  out_size: 8256
  num_basis: 128

train:
  batch_size: 32
  epochs: 300
  lr: 0.001
  # log_path: "/home/yixuan.sun/projects/neuralPrecond/MatrixPreNet/logs/"
  log_path: "/Users/yixuan.sun/Documents/projects/Preconditioners/MatrixPreNet/logs/"
  loss: "CG_loss"

