wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 10000
h_ch:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698348602.168557
    t:
      1:
      - 1
      - 12
      - 45
      - 55
      2:
      - 1
      - 12
      - 45
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.6
      5: 0.15.12
      8:
      - 4
      - 5
      13: darwin-arm64
