calls:
- max_evals: 500
  timeout: null
search:
  acq_func: UCBd
  acq_optimizer: mixedga
  acq_optimizer_freq: 1
  evaluator:
    num_workers: 1
    type: SerialEvaluator
  filter_duplicated: true
  filter_failures: min
  initial_point_generator: random
  initial_points:
  - activation: relu
    batch_size: 32
    dropout_rate: 0.0
    hidden_dims: 64
    lr: 0.001
    num_layers: 3
  kappa: 5.0
  kwargs: {}
  log_dir: hpo_precondFNN
  max_failures: 100
  moo_lower_bounds: null
  moo_scalarization_strategy: Chebyshev
  moo_scalarization_weight: null
  multi_point_strategy: cl_max
  n_initial_points: 10
  n_jobs: 1
  n_points: 10000
  objective_scaler: identity
  problem:
    conditions: []
    forbiddens: []
    format_version: 0.4
    hyperparameters:
    - choices:
      - relu
      - swish
      - sigmoid
      - softplus
      - prelu
      default_value: relu
      meta: null
      name: activation
      type: categorical
      weights: null
    - default_value: 32
      log: false
      lower: 1
      meta: null
      name: batch_size
      type: uniform_int
      upper: 256
    - default_value: 0.0
      log: false
      lower: 0.0
      meta: null
      name: dropout_rate
      type: uniform_float
      upper: 0.5
    - default_value: 64
      log: false
      lower: 16
      meta: null
      name: hidden_dims
      type: uniform_int
      upper: 128
    - default_value: 0.001
      log: true
      lower: 1.0e-05
      meta: null
      name: lr
      type: uniform_float
      upper: 0.1
    - default_value: 3
      log: false
      lower: 1
      meta: null
      name: num_layers
      type: uniform_int
      upper: 20
    name: null
    python_module_version: 1.2.0
  random_state: null
  scheduler:
    kappa_final: 0.0001
    period: 50
    type: periodic-exp-decay
  stopper: null
  surrogate_model: ET
  surrogate_model_kwargs: null
  sync_communication: false
  type: CBO
  update_prior: false
  update_prior_quantile: 0.1
  verbose: 0
  xi: 0.001
