double_precision: True

model:
  num_heads: 2 # heads need to be a factor of out_feat
  in_feat: 1
  out_feat: 2
  num_layers: 3
  num_dense_layers: 3
  dense_h_dim: 1024
  num_nnzs: 1792

data:
  path: "../data/U1_DD_matrices.pt"
  batch_size: 128
  num_workers: 4
  train_size: 0.8


train:
  optimizer: "adam"
  loss_name: "ConditionNumberLoss"
  lr: 0.0001
  epochs: 100
  save_model: True


