double_precision: True

model:
  num_mp_blocks: 2
  node_dim: 1
  edge_dim: 1
  hn_dim: 8
  he_dim: 8

data:
  path: "../data/U1_DD_matrices.pt"
  num_workers: 4
  train_size: 0.8


train:
  optimizer: "adam"
  loss_name: "ConditionNumberLoss"
  lr: 0.0001
  epochs: 100
  batch_size: 128
  save_model: True


